### ISSUE TITLE
RSS Feed for newsletters

### ISSUE THREAD

**Issue by nilsandrey** [xojoc/discussions#2]
I would like to have an RSS Feed link for the newsletters, so I can add it to Feedly instead of my mailbox.

**Comment by xojoc** [comment]
Hi,
the idea is to add that option as a premium feature. Alternatively you can use an external service like feedbin.com, kill the newsletter or even Feedly (I think).

Thanks

**Comment by xojoc** [comment]
For the interested I've finally put together a premium plan with RSS feeds: https://discu.eu/premium/
